#### Python 数据科学

##### Numpy
1. 说明
    * 提供多维数组对象以及一系列操作数组的函数
    
2. 核型数据结构
    * ndarray ：用于存储具有相同数据结构的多维数组

In [2]:
import numpy as np

In [9]:
np.ndarray?

In [4]:
d0 = np.array([[1,2],[3,4]])

In [10]:
d0

array([[1, 2],
       [3, 4]])

In [11]:
d0[0]

array([1, 2])

In [12]:
d0[0][0]

1

In [13]:
d0[0,0]

1

In [18]:
d0[(d0 > 1)&(d0 < 5)]

array([2, 3, 4])