##### softMax

In [1]:
import numpy as np

In [3]:
vector = np.array([-1, -3, 10, 14])

In [7]:
def softMax(vector) : 
    exp = np.exp(vector)
    return exp / np.sum(vector)

In [8]:
softMax(vector)

array([1.83939721e-02, 2.48935342e-03, 1.10132329e+03, 6.01302142e+04])

In [9]:
vector = np.array([-1, 11231, 10, 14, 999, 123142])

In [11]:
vector

array([    -1,  11231,     10,     14,    999, 123142])

In [12]:
softMax(vector)

array([2.71708291e-06,            inf, 1.62683007e-01, 8.88219125e+00,
                  inf,            inf])

In [13]:
def softMax(vector) : 
    vector -= np.max(vector)
    exp = np.exp(vector)
    return exp / np.sum(vector)

In [14]:
softMax(vector)

array([-0.0000000e+00, -0.0000000e+00, -0.0000000e+00, -0.0000000e+00,
       -0.0000000e+00, -1.6571189e-06])